### ISSUE TITLE
发现两个BUG

### ISSUE THREAD

**Issue by iamqq23ue** [WeBankFinTech/EventMesh#154]
1，eventmesh打包版安装后，启动脚本在linux不能运行，需要在ue中重新编辑在拷贝到linux。
2，sh runadmin.sh updateTopic  -c ${ClusterName} -t ${topic} -n ${namesrvAddr} 时会报缺少tools.yml文件,从rocketmq拷贝了一个之后问题解决

**Comment by qqeasonchen** [comment]
good question, we will check and fix it
