### ISSUE TITLE
Specification of code structure and file naming

### ISSUE THREAD

**Issue by xwm1992** [WeBankFinTech/EventMesh#265]
Currently, there are some confusing names for files, properties and configurations, such as WEMQ, Access, Proxy, etc. Please normalize the naming of these contents.

**Comment by MajorHe1** [comment]
How to normalize?

**Comment by xwm1992** [comment]
You do this optimization for code under the 1.3.0 branch

**Comment by qqeasonchen** [comment]
@xwm1992 @MajorHe1 I suggest do it on 1.2.2 so it can be published on the coming release of 1.2.
